import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { parseCsv } from "../src/lib/analyzer/parse.ts";
import type { Candle as EngineCandle } from "../src/lib/analyzer/types.ts";
import { calibrate } from "../src/lib/synth/calibrate.ts";
import type { CalibrationProfile } from "../src/lib/synth/types.ts";

const args = process.argv.slice(2);
const inputPaths = args.filter((arg) => !arg.startsWith("--"));
if (inputPaths.length === 0) {
  throw new Error(
    "Pass explicit source CSV path(s); calibration will not fall back to a partial baseline.",
  );
}
const paths = inputPaths;
const profileOut = "src/lib/synth/profile.json";
const bundledProfileOut = "src/lib/synth/profile-default.ts";

function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function toSyntheticCandle(
  candle: EngineCandle,
  path: string,
): { datetime: string; open: number; high: number; low: number; close: number } {
  if (
    candle.open === undefined ||
    candle.high === undefined ||
    candle.low === undefined ||
    candle.close === undefined ||
    candle.invalid
  ) {
    throw new Error(
      `${path}: invalid core OHLC row at ${candle.datetime}: ${candle.invalid ?? "missing OHLC"}`,
    );
  }
  return {
    datetime: candle.datetime,
    open: candle.open,
    high: candle.high,
    low: candle.low,
    close: candle.close,
  };
}

const allCandles: ReturnType<typeof toSyntheticCandle>[] = [];
const fileSummaries: CalibrationProfile["source"]["files"] = [];
const metadataAge: string[] = [];
const metadataAtr: string[] = [];
for (const path of paths) {
  const text = readFileSync(path, "utf8");
  const firstLine = text.split(/\r?\n/, 1)[0] ?? "";
  const openBrace = firstLine.indexOf("{");
  const metadata =
    openBrace >= 0 ? (JSON.parse(firstLine.slice(openBrace)) as Record<string, unknown>) : {};
  const parsed = parseCsv(text);
  if (parsed.metadataError) throw new Error(`${path}: ${parsed.metadataError}`);
  if (parsed.candles.some((candle) => candle.invalid)) {
    const firstInvalid = parsed.candles.find((candle) => candle.invalid)!;
    throw new Error(`${path}: invalid row at ${firstInvalid.datetime}: ${firstInvalid.invalid}`);
  }
  const converted = parsed.candles.map((candle) => toSyntheticCandle(candle, path));
  if (converted.length === 0) throw new Error(`${path}: no candle rows`);
  // Preserve caller/file order and fail on a seam; no implicit sorting or de-duplication.
  const previous = allCandles.at(-1);
  const first = converted[0]!;
  if (previous && first.datetime <= previous.datetime) {
    throw new Error(
      `file seam is not strictly increasing: prior=${previous.datetime}, next=${first.datetime} (${path}); input was not sorted or deduplicated`,
    );
  }
  allCandles.push(...converted);
  fileSummaries.push({
    path,
    sha256: sha256(text),
    bars: converted.length,
    start: converted[0]!.datetime,
    end: converted[converted.length - 1]!.datetime,
  });
  if (metadata["data_age"] !== undefined) metadataAge.push(String(metadata["data_age"]));
  if (metadata["atr_method"] !== undefined) metadataAtr.push(String(metadata["atr_method"]));
}

const profile = calibrate(allCandles);
profile.source.files = fileSummaries;
profile.source.provenance =
  paths.length === 1 && paths[0] === "artifacts/baseline-xauusd-ohlc.csv"
    ? "repository-baseline-only"
    : "user-supplied-local-data";
const archiveStart = "2020-01-24";
const archiveEnd = "2026-10-01";
const coversRegisteredArchiveWindow =
  profile.source.span.start.slice(0, 10) <= archiveStart &&
  profile.source.span.end.slice(0, 10) >= archiveEnd;
profile.source.coverageWarning = coversRegisteredArchiveWindow
  ? `Observed timestamps reach the registered archive window ${archiveStart} through ${archiveEnd}; missing dates and intraday gaps remain recorded and were not filled.`
  : `Available local inputs cover ${profile.source.span.start} through ${profile.source.span.end}; the registered archive window is ${archiveStart} through ${archiveEnd}. This is a partial-sample calibration and must not be represented as full-window coverage.`;
profile.source.metadataDataAge = [...new Set(metadataAge)].join("; ") || undefined;
profile.source.metadataAtrMethod = [...new Set(metadataAtr)].join("; ") || undefined;

const profileJson = `${JSON.stringify(profile, null, 2)}\n`;
writeFileSync(profileOut, profileJson, "utf8");
const compact = JSON.stringify(profile).replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
writeFileSync(
  bundledProfileOut,
  `import type { CalibrationProfile } from "./types";\n\n// Generated by scripts/synth-calibrate.ts from the adjacent, self-contained profile.json.\nconst embedded = String.raw\`${compact}\`;\nexport const DEFAULT_PROFILE = JSON.parse(embedded) as CalibrationProfile;\n`,
  "utf8",
);

console.log(
  JSON.stringify(
    {
      profilePath: profileOut,
      bundledRuntimeProfile: bundledProfileOut,
      inputFiles: fileSummaries,
      canonicalCandlesSha256: profile.source.canonicalCandlesSha256,
      bars: profile.sample.bars,
      span: profile.source.span,
      barsPerYear: profile.source.barsPerYear,
      coverageWarning: profile.source.coverageWarning,
      metadataDataAge: profile.source.metadataDataAge,
      metadataAtrMethod: profile.source.metadataAtrMethod,
      wilderAtrPercent: profile.sample.atrPercent.quantiles,
      rolling60DayDriftLogReturn: profile.sample.rolling60DayDriftLogReturn.quantiles,
      varianceRatio8: profile.sample.varianceRatio8.quantiles,
      varianceRatio16: profile.sample.varianceRatio16.quantiles,
      lag1Autocorrelation: profile.sample.lag1ReturnAutocorrelation.quantiles,
      completeWeeklyBlocks: profile.resampling.completeWeeks.length,
    },
    null,
    2,
  ),
);
