/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as MapGeneratorRouteImport } from './routes/map-generator'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as ApiMarketDataRouteImport } from './routes/api/market-data'
import { Route as ApiMt5RouteImport } from './routes/api/mt5'
import { Route as ApiMarketDataHealthRouteImport } from './routes/api/market-data.health'
import { Route as ApiMt5BridgeRouteImport } from './routes/api/mt5.bridge'
import { Route as ApiMt5EaRouteImport } from './routes/api/mt5.ea'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const MapGeneratorRoute = MapGeneratorRouteImport.update({
  id: '/map-generator',
  path: '/map-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRoute,
} as any)
const ApiMarketDataRoute = ApiMarketDataRouteImport.update({
  id: '/api/market-data',
  path: '/api/market-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMt5Route = ApiMt5RouteImport.update({
  id: '/api/mt5',
  path: '/api/mt5',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketDataHealthRoute = ApiMarketDataHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ApiMarketDataRoute,
} as any)
const ApiMt5BridgeRoute = ApiMt5BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => ApiMt5Route,
} as any)
const ApiMt5EaRoute = ApiMt5EaRouteImport.update({
  id: '/ea',
  path: '/ea',
  getParentRoute: () => ApiMt5Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/backtest': typeof BacktestRoute
  '/generator': typeof GeneratorRoute
  '/map-generator': typeof MapGeneratorRoute
  '/api/market-data': typeof ApiMarketDataRouteWithChildren
  '/api/mt5': typeof ApiMt5RouteWithChildren
  '/analysis/': typeof AnalysisIndexRoute
  '/api/market-data/health': typeof ApiMarketDataHealthRoute
  '/api/mt5/bridge': typeof ApiMt5BridgeRoute
  '/api/mt5/ea': typeof ApiMt5EaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/generator': typeof GeneratorRoute
  '/map-generator': typeof MapGeneratorRoute
  '/api/market-data': typeof ApiMarketDataRouteWithChildren
  '/api/mt5': typeof ApiMt5RouteWithChildren
  '/analysis': typeof AnalysisIndexRoute
  '/api/market-data/health': typeof ApiMarketDataHealthRoute
  '/api/mt5/bridge': typeof ApiMt5BridgeRoute
  '/api/mt5/ea': typeof ApiMt5EaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/backtest': typeof BacktestRoute
  '/generator': typeof GeneratorRoute
  '/map-generator': typeof MapGeneratorRoute
  '/api/market-data': typeof ApiMarketDataRouteWithChildren
  '/api/mt5': typeof ApiMt5RouteWithChildren
  '/analysis/': typeof AnalysisIndexRoute
  '/api/market-data/health': typeof ApiMarketDataHealthRoute
  '/api/mt5/bridge': typeof ApiMt5BridgeRoute
  '/api/mt5/ea': typeof ApiMt5EaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/backtest'
    | '/generator'
    | '/map-generator'
    | '/api/market-data'
    | '/api/mt5'
    | '/analysis/'
    | '/api/market-data/health'
    | '/api/mt5/bridge'
    | '/api/mt5/ea'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/generator'
    | '/map-generator'
    | '/api/market-data'
    | '/api/mt5'
    | '/analysis'
    | '/api/market-data/health'
    | '/api/mt5/bridge'
    | '/api/mt5/ea'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/backtest'
    | '/generator'
    | '/map-generator'
    | '/api/market-data'
    | '/api/mt5'
    | '/analysis/'
    | '/api/market-data/health'
    | '/api/mt5/bridge'
    | '/api/mt5/ea'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  BacktestRoute: typeof BacktestRoute
  GeneratorRoute: typeof GeneratorRoute
  MapGeneratorRoute: typeof MapGeneratorRoute
  ApiMarketDataRoute: typeof ApiMarketDataRouteWithChildren
  ApiMt5Route: typeof ApiMt5RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-generator': {
      id: '/map-generator'
      path: '/map-generator'
      fullPath: '/map-generator'
      preLoaderRoute: typeof MapGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/api/market-data': {
      id: '/api/market-data'
      path: '/api/market-data'
      fullPath: '/api/market-data'
      preLoaderRoute: typeof ApiMarketDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mt5': {
      id: '/api/mt5'
      path: '/api/mt5'
      fullPath: '/api/mt5'
      preLoaderRoute: typeof ApiMt5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-data/health': {
      id: '/api/market-data/health'
      path: '/health'
      fullPath: '/api/market-data/health'
      preLoaderRoute: typeof ApiMarketDataHealthRouteImport
      parentRoute: typeof ApiMarketDataRoute
    }
    '/api/mt5/bridge': {
      id: '/api/mt5/bridge'
      path: '/bridge'
      fullPath: '/api/mt5/bridge'
      preLoaderRoute: typeof ApiMt5BridgeRouteImport
      parentRoute: typeof ApiMt5Route
    }
    '/api/mt5/ea': {
      id: '/api/mt5/ea'
      path: '/ea'
      fullPath: '/api/mt5/ea'
      preLoaderRoute: typeof ApiMt5EaRouteImport
      parentRoute: typeof ApiMt5Route
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

interface ApiMarketDataRouteChildren {
  ApiMarketDataHealthRoute: typeof ApiMarketDataHealthRoute
}

const ApiMarketDataRouteChildren: ApiMarketDataRouteChildren = {
  ApiMarketDataHealthRoute: ApiMarketDataHealthRoute,
}

const ApiMarketDataRouteWithChildren = ApiMarketDataRoute._addFileChildren(
  ApiMarketDataRouteChildren,
)

interface ApiMt5RouteChildren {
  ApiMt5BridgeRoute: typeof ApiMt5BridgeRoute
  ApiMt5EaRoute: typeof ApiMt5EaRoute
}

const ApiMt5RouteChildren: ApiMt5RouteChildren = {
  ApiMt5BridgeRoute: ApiMt5BridgeRoute,
  ApiMt5EaRoute: ApiMt5EaRoute,
}

const ApiMt5RouteWithChildren =
  ApiMt5Route._addFileChildren(ApiMt5RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  BacktestRoute: BacktestRoute,
  GeneratorRoute: GeneratorRoute,
  MapGeneratorRoute: MapGeneratorRoute,
  ApiMarketDataRoute: ApiMarketDataRouteWithChildren,
  ApiMt5Route: ApiMt5RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
